### ISSUE TITLE
Running EthStats for any custom network

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [Alethio/ethstats-cli#18]
Hello Alethio team!
I was wondering if I could run the ethstats monitoring for any custom node (not only mainnet, goerli and rinkeby), because as stated in this article https://medium.com/alethio/a-guide-to-deploying-alethios-free-open-source-products-18216617722e , I should be able to "With it you could easily plug into any PoW and PoA network."

However, I am trying to run the `ethstats-cli` and connect it to a node (which is not running on `mainnet`, `goerli` or `rinkeby`) and I am unable to do it, because I have to register the node.

Is there a workaround to this or am I missing something?

Thank you!

**Comment by baxy** [comment]
Hi Daniel, 
Yes, you can run ethstats-cli on any ethereum based node, on any PoW or PoA networks. If you have a private network you want to monitor you'll need to install the entire EthStats stack, server (https://github.com/Alethio/ethstats-network-server) and client (https://github.com/Alethio/ethstats-cli). In the Medium article is detailed how to install both of them. Assuming you run ethstats-cli in a docker container like in the article, the node registration is done automatically with the condition that the server is deployed and configured correctly for you private network. Very important is to set the NETWORK_ID env var in the server's docker-compose file. Also you need to specify ethstats-cli to connect to your EthStats server (see "--server-url" in the CLI options https://github.com/Alethio/ethstats-cli#cli-options), because by default it will try to connect to our server on mainnet. 

Cheers

**Comment by Daniel-K-Ivanov** [comment]
Hello Adrian!
Thank you for the information. I will try and run it the way you described. 

Cheers
